<?php
declare(strict_types=1);
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$root=__DIR__;if(!is_file($root.'/config.php')){if(!str_starts_with($path,'/install')){header('Location: /install/',true,302);exit;}return;}$config=require $root.'/config.php';require $root.'/app/core.php';require $root.'/app/providers.php';require $root.'/app/api.php';require $root.'/app/public.php';
header('X-Content-Type-Options: nosniff');header('Referrer-Policy: strict-origin-when-cross-origin');header("Permissions-Policy: camera=(), microphone=(), geolocation=()");
try{
 if($path==='/api/catalog'&&$_SERVER['REQUEST_METHOD']==='GET')out(['records'=>records("SELECT * FROM cv_catalog WHERE kind IN ('movie','series') AND (status='published' OR (status='scheduled' AND publish_at<=?)) ORDER BY featured DESC,updated_at DESC LIMIT 2000",[ms()])]);
 if(preg_match('~^/admin/api/([a-z-]+)$~',$path,$m))api($m[1]);
 if($path==='/admin/assets.css'){header('Content-Type: text/css; charset=utf-8');readfile($root.'/app/admin.css');exit;}
 if($path==='/admin/assets.js'){header('Content-Type: text/javascript; charset=utf-8');readfile($root.'/app/admin.js');exit;}
 if($path==='/admin/login'){
  startSession();if(user())go('/admin');$error='';if($_SERVER['REQUEST_METHOD']==='POST'){checkCsrf($_POST['csrf']??null);$key=hash('sha256',($_SERVER['REMOTE_ADDR']??'unknown').':login');$limit=one('SELECT * FROM cv_limits WHERE id=?',[$key]);$now=time();if($limit&&$limit['reset_at']>$now&&$limit['attempts']>=8)throw new AppError('Too many attempts. Try again later.',429);$u=one('SELECT * FROM cv_users WHERE username=?',[strtolower(txt($_POST['username']??'',60))]);if(!$u||!$u['active']||!password_verify((string)($_POST['password']??''),$u['verifier'])){run('INSERT INTO cv_limits VALUES (?,1,?) ON DUPLICATE KEY UPDATE attempts=IF(reset_at<?,attempts+1,1),reset_at=IF(reset_at<?,reset_at,?)',[$key,$now+900,$now,$now,$now+900]);$error='Invalid username or password.';}else{run('DELETE FROM cv_limits WHERE id=?',[$key]);session_regenerate_id(true);$_SESSION['csrf']=bin2hex(random_bytes(32));$_SESSION['user']=['id'=>$u['id'],'username'=>$u['username'],'role'=>$u['role'],'version'=>(int)$u['version']];$_SESSION['expires']=time()+3600;go('/admin');}}
  echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>CineVault Login</title><style>body{margin:0;background:#08090b;color:white;font:16px system-ui}.box{max-width:420px;margin:12vh auto;padding:32px;background:#111317;border:1px solid #30343b;border-radius:16px}label{display:grid;gap:7px;margin:16px 0;font-weight:700}input{padding:13px;background:#08090b;color:white;border:1px solid #3b4048;border-radius:8px;font:inherit}button{width:100%;padding:13px;background:#e74733;color:white;border:0;border-radius:9px;font-weight:800}.error{color:#ff9f94}</style></head><body><main class="box"><h1>Administration</h1><p class="error">'.esc($error).'</p><form method="post"><input type="hidden" name="csrf" value="'.esc(csrf()).'"><label>Username<input name="username" required autocomplete="username"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button>Sign in</button></form><p><a href="/">Return to site</a></p></main></body></html>';exit;
 }
 if($path==='/admin/logout'&&$_SERVER['REQUEST_METHOD']==='POST'){checkCsrf($_POST['csrf']??null);$_SESSION=[];session_destroy();go('/admin/login');}
 if($path==='/admin'||$path==='/admin/'){$u=requireUser();$html=file_get_contents($root.'/app/admin.html');$html=str_replace(['/admin/assets.css','/admin/assets.js','__CSRF__','__USERNAME__','__ROLE__','__ROLE_LABEL__'],['/admin/assets.css?v=20260919-2','/admin/assets.js?v=20260919-2',esc(csrf()),esc($u['username']),esc($u['role']),$u['role']==='admin'?'Master administrator':'Moderator'],$html);header('Content-Type: text/html; charset=utf-8');echo $html;exit;}
 if(preg_match('~^/admin/preview/([a-f0-9-]+)$~',$path,$m)){$u=requireUser();$r=decodeRow(one('SELECT * FROM cv_catalog WHERE id=?',[$m[1]]));if(!$r)throw new AppError('Title not found.',404);echo titlePage($r,true);exit;}
 if(preg_match('~^/title/(.+)$~',$path,$m)&&$_SERVER['REQUEST_METHOD']==='GET'){$r=one('SELECT * FROM cv_catalog WHERE slug=?',[rawurldecode($m[1])]);$r=$r?visible($r['id']):null;if(!$r)throw new AppError('Title not found.',404);metric('view',$r['id']);echo titlePage($r);exit;}
 if(preg_match('~^/go/([a-f0-9-]+)(/continue)?$~',$path,$m)){$l=decodeRow(one('SELECT * FROM cv_downloads WHERE id=? AND active=1',[$m[1]]));$title=$l?visible($l['title_id']):null;if(!$l||!$title)throw new AppError('Download link unavailable.',404);startSession();$_SESSION['visitor']??=bin2hex(random_bytes(16));$s=site();if(!empty($m[2])&&$_SERVER['REQUEST_METHOD']==='POST'){originCheck();$t=token($_POST['token']??'','gateway');if(($t['id']??'')!==$l['id']||($t['visitor']??'')!==$_SESSION['visitor']||($t['ready']??0)>time())throw new AppError('Wait for the countdown or reopen this page.',409);$day=gmdate('Y-m-d');metric('download',$l['id']);metric('download-title',$title['id']);$hash=hash_hmac('sha256',$_SESSION['visitor'].':'.$day,$config['secret']);run('INSERT IGNORE INTO cv_visitors VALUES (?,?,?,?)',[$day.':'.$l['id'].':'.$hash,$day,$l['id'],$hash]);header('Location: '.$l['url'],true,303);exit;}if(!empty($m[2])||$_SERVER['REQUEST_METHOD']!=='GET')throw new AppError('Not found.',404);$seconds=max(0,min(300,(int)$s['gatewaySeconds']));$ready=time()+$seconds;$t=signToken(['purpose'=>'gateway','id'=>$l['id'],'visitor'=>$_SESSION['visitor'],'ready'=>$ready,'exp'=>time()+900]);$body=adHtml('gateway-top',$s).'<main class="title-page gateway-page"><section class="title-info gateway-card">'.(!empty($title['data']['backdrop'])?'<img class="gateway-backdrop" src="'.esc($title['data']['backdrop']).'" alt="">':'').'<div class="gateway-content"><p>EXTERNAL DOWNLOAD</p><h1>'.esc($title['title']).'</h1><p>'.esc(implode(' · ',array_filter([$l['name'],$l['data']['quality']??'',$l['data']['size']??'']))).'</p><p>You will continue to an external website.</p><form method="post" action="/go/'.esc($l['id']).'/continue"><input type="hidden" name="token" value="'.esc($t).'"><button class="primary" data-ready="'.$ready.'" data-seconds="'.$seconds.'">Continue to download</button></form><p id="countdown-note"></p><p><a href="/title/'.rawurlencode($title['slug']).'">Back to title</a></p></div></section></main><script src="/assets/gateway.js?v=20260919-1" defer></script>';echo shell($s,'Download · '.$title['title'],$body);exit;}
 if($path==='/report'&&$_SERVER['REQUEST_METHOD']==='POST'){originCheck();$t=token($_POST['token']??'','report');$l=one('SELECT * FROM cv_downloads WHERE id=? AND active=1',[$t['id']??'']);if(!$l||!visible($l['title_id']))throw new AppError('Link unavailable.',404);$reason=choice($_POST['reason']??null,['Link not working','File removed','Wrong movie','Wrong quality','Other'],'Other');$now=ms();run("INSERT INTO cv_reports VALUES (?,?,?,'open',?,?)",[uid(),$l['id'],$reason,$now,$now]);echo shell(site(),'Report submitted','<main class="title-page"><section class="title-info"><h1>Report submitted</h1><p>The site team can review this link.</p><a href="/">Return home</a></section></main>');exit;}
 if(($path==='/'||$path==='/index.php')&&$_SERVER['REQUEST_METHOD']==='GET'){$s=site();$h=file_get_contents($root.'/app/home.html');$h=str_replace(['styles.css','app.js','/ads.js'],['/assets/styles.css?v=20260913-5','/assets/app.js','/assets/ads.js'],$h);$h=preg_replace('~<title>.*?</title>~','<title>'.esc($s['name']).' — Movies & Series</title>',$h);$h=preg_replace('~<a class="brand"[^>]*>.*?</a>~s','<a class="brand" href="/">'.brand($s).'</a>',$h);$h=preg_replace('~<footer>.*?</footer>~s',footerHtml($s),$h);$h=str_replace('</head>','<style>'.brandCss($s).homeHeroCss().'</style></head>',$h);foreach(['homepage-top','homepage-middle','sidebar','footer'] as $slot)$h=str_replace('<div data-slot="'.$slot.'"></div>',adHtml($slot,$s),$h);echo $h;exit;}
 throw new AppError('Page not found.',404);
}catch(AppError $e){if(str_starts_with($path,'/admin/api/'))out(['error'=>$e->getMessage()],$e->getCode()?:400);http_response_code($e->getCode()?:400);echo shell(site(),'Error','<main class="title-page"><section class="title-info"><h1>'.esc($e->getMessage()).'</h1><p><a href="/">Return home</a></p></section></main>');}catch(Throwable $e){if(str_starts_with($path,'/admin/api/'))out(['error'=>'The server could not complete the request.'],500);http_response_code(500);echo 'Server error. Check hosting error logs.';}
