<?php
function providers(): array {return array_replace(['tvmaze'=>['enabled'=>true,'language'=>'en-US','region'=>'US'],'tmdb'=>['enabled'=>false,'language'=>'en-US','region'=>'US'],'omdb'=>['enabled'=>false,'language'=>'en-US','region'=>'US']],setting('providers'));}
function adminState(array $u): array {$admin=$u['role']==='admin';$p=providers();foreach($p as &$v){$v['keyConfigured']=!empty($v['secret']);unset($v['secret']);$v['lastTest']??=null;}unset($v);$day=gmdate('Y-m-d');return ['records'=>records('SELECT * FROM cv_catalog ORDER BY updated_at DESC LIMIT 2000'),'links'=>records('SELECT * FROM cv_downloads ORDER BY updated_at DESC LIMIT 2000'),'watches'=>records('SELECT * FROM cv_watches ORDER BY updated_at DESC LIMIT 2000'),'ads'=>$admin?records('SELECT * FROM cv_ads ORDER BY updated_at DESC LIMIT 500'):[],'reports'=>records('SELECT * FROM cv_reports ORDER BY created_at DESC LIMIT 1000'),'logs'=>records('SELECT * FROM cv_activity ORDER BY created_at DESC LIMIT 60'),'site'=>$admin?site():['name'=>site()['name']],'providers'=>$p,'metrics'=>records('SELECT kind,SUM(count) total FROM cv_metrics WHERE day=? GROUP BY kind',[$day]),'counts'=>records('SELECT kind,status,COUNT(*) total FROM cv_catalog GROUP BY kind,status'),'downloadStats'=>records("SELECT target,SUM(count) total,SUM(CASE WHEN day=? THEN count ELSE 0 END) today FROM cv_metrics WHERE kind='download' GROUP BY target ORDER BY total DESC",[$day]),'titleStats'=>records("SELECT target,SUM(count) total FROM cv_metrics WHERE kind='download-title' GROUP BY target ORDER BY total DESC"),'visitorStats'=>records('SELECT day,COUNT(DISTINCT visitor) total FROM cv_visitors GROUP BY day ORDER BY day DESC LIMIT 30'),'moderators'=>$admin?records("SELECT id,username,name,active,created_at,updated_at FROM cv_users WHERE role='moderator' ORDER BY created_at DESC"):[],'role'=>$u['role']];}
function saveCatalog(array $b): array {
 $id=$b['id']??uid();$old=isset($b['id'])?one('SELECT * FROM cv_catalog WHERE id=? FOR UPDATE',[$id]):null;if(isset($b['id'])&&!$old)throw new AppError('Title not found.',404);if($old&&(int)($b['updated_at']??0)!==(int)$old['updated_at'])throw new AppError('Another change was saved. Reload this title.',409);
 $kind=choice($b['kind']??null,['movie','series','season','episode'],'movie');$title=txt($b['title']??'');if(!$title)throw new AppError('Enter a title.');$slug=trim(preg_replace('/[^\p{L}\p{N}]+/u','-',mb_strtolower(txt(($b['slug']??'')?:$title,160))),'-')?:$id;if(one('SELECT id FROM cv_catalog WHERE slug=? AND id<>?',[$slug,$id]))throw new AppError('This slug is already used.',409);
 $status=choice($b['status']??null,['draft','published','scheduled'],'draft');$publish=dateval($b['publish_at']??0);if($status==='scheduled'&&!$publish)throw new AppError('Choose a publication time.');$parent=in_array($kind,['season','episode'])?txt($b['parent_id']??'',36):null;if($parent!==null){$p=one('SELECT kind FROM cv_catalog WHERE id=?',[$parent]);if(!$p||$p['kind']!==($kind==='season'?'series':'season'))throw new AppError('Choose the correct parent series or season.');}if($old&&$old['kind']!==$kind&&one('SELECT id FROM cv_catalog WHERE parent_id=? LIMIT 1',[$id]))throw new AppError('Move or delete child titles before changing this type.');
 $d=$b['data']??[];$data=[];foreach(['originalTitle'=>200,'overview'=>20000,'releaseDate'=>30,'ratingProvider'=>30,'cast'=>5000,'director'=>1000,'writers'=>1000,'quality'=>30,'seoTitle'=>150,'metaDescription'=>300,'providerId'=>100,'imdbId'=>30] as $k=>$max)$data[$k]=txt($d[$k]??'',$max);foreach(['genres','languages','countries'] as $k)$data[$k]=listval($d[$k]??[]);$data['collections']=array_values(array_intersect(listval($d['collections']??[]),['anime','superhero']));foreach(['poster','backdrop','trailer','sourceUrl'] as $k)$data[$k]=httpsUrl($d[$k]??'');foreach(['year'=>2200,'runtime'=>10000,'rating'=>10,'number'=>10000] as $k=>$max)$data[$k]=num($d[$k]??null,0,$max);$data['provider']=choice($d['provider']??null,['','tvmaze','tmdb','omdb'],'');$ts=ms();
 if($old)run('UPDATE cv_catalog SET kind=?,title=?,slug=?,status=?,publish_at=?,featured=?,parent_id=?,data=?,updated_at=? WHERE id=?',[$kind,$title,$slug,$status,$publish,!empty($b['featured'])?1:0,$parent,json_encode($data),$ts,$id]);else run('INSERT INTO cv_catalog VALUES (?,?,?,?,?,?,?,?,?,?,?)',[$id,$kind,$title,$slug,$status,$publish,!empty($b['featured'])?1:0,$parent,json_encode($data),$ts,$ts]);
 $watch=$b['watches']??[];if(!is_array($watch)||count($watch)>20)throw new AppError('Use up to 20 watch links.');$seen=[];foreach($watch as $l){if(empty($l['id'])&&empty($l['url']))continue;if(!empty($l['id'])){if(isset($seen[$l['id']]))throw new AppError('Duplicate watch link.');$seen[$l['id']]=1;$oldWatch=one('SELECT * FROM cv_watches WHERE id=? AND title_id=? FOR UPDATE',[$l['id'],$id]);if(!$oldWatch)throw new AppError('Watch link does not belong to this title.',409);$l=array_replace($oldWatch,$l);}$l['title_id']=$id;saveWatch($l);}
 $links=$b['downloads']??(isset($b['download'])?[$b['download']]:[]);if(!is_array($links)||count($links)>50)throw new AppError('Use up to 50 links per save.');$seen=[];foreach($links as $l){if(empty($l['id'])&&empty($l['url']))continue;if(!empty($l['id'])){if(isset($seen[$l['id']]))throw new AppError('Duplicate link.');$seen[$l['id']]=true;$existing=decodeRow(one('SELECT * FROM cv_downloads WHERE id=? AND title_id=? FOR UPDATE',[$l['id'],$id]));if(!$existing)throw new AppError('Link does not belong to this title.',409);$l=array_replace($existing,$l);} $l['title_id']=$id;$l['name']=$l['name']??'Download';$l['active']=$l['active']??true;saveDownload($l);}
 audit($old?'Title updated':'Title created',$title);return ['id'=>$id];
}
function saveDownload(array $b): array {$id=$b['id']??uid();if(isset($b['id'])&&!one('SELECT id FROM cv_downloads WHERE id=?',[$id]))throw new AppError('Link not found.',404);if(!one('SELECT id FROM cv_catalog WHERE id=?',[$b['title_id']??'']))throw new AppError('Choose an existing title.');$name=txt($b['name']??'',100);if(!$name)throw new AppError('Enter a server name.');$url=httpsUrl($b['url']??'',true);$d=$b['data']??[];$data=[];foreach(['quality','size','language','format','source'] as $k)$data[$k]=txt($d[$k]??'',100);$data['priority']=num($d['priority']??0,0,1000);$ts=ms();run('INSERT INTO cv_downloads VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title_id=VALUES(title_id),name=VALUES(name),url=VALUES(url),active=VALUES(active),data=VALUES(data),updated_at=VALUES(updated_at)',[$id,$b['title_id'],$name,$url,!empty($b['active'])?1:0,json_encode($data),$ts,$ts]);audit('Download link saved',$name);return ['id'=>$id];}
function saveWatch(array $b): array {$id=$b['id']??uid();if(isset($b['id'])&&!one('SELECT id FROM cv_watches WHERE id=?',[$id]))throw new AppError('Watch link not found.',404);if(!one('SELECT id FROM cv_catalog WHERE id=?',[$b['title_id']??'']))throw new AppError('Choose an existing title.');$name=txt($b['name']??'Watch now',100)?:'Watch now';$url=httpsUrl($b['url']??'',true);$ts=ms();run('INSERT INTO cv_watches VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title_id=VALUES(title_id),name=VALUES(name),url=VALUES(url),active=VALUES(active),updated_at=VALUES(updated_at)',[$id,$b['title_id'],$name,$url,!empty($b['active'])?1:0,$ts,$ts]);audit('Watch link saved',$name);return ['id'=>$id];}
function deleteTitle(string $id,int $depth=0): void {if($depth>4)throw new AppError('Invalid title hierarchy.');foreach(rows('SELECT id FROM cv_catalog WHERE parent_id=?',[$id]) as $r)deleteTitle($r['id'],$depth+1);run('DELETE FROM cv_catalog WHERE id=?',[$id]);}
function api(string $action): never {
 $u=requireUser();if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='state')out(adminState($u));if($_SERVER['REQUEST_METHOD']!=='POST')throw new AppError('Method not allowed.',405);checkCsrf($_SERVER['HTTP_X_CSRF_TOKEN']??null);$raw=file_get_contents('php://input');if(strlen($raw)>800000)throw new AppError('Request too large.',413);$b=json_decode($raw,true);if(!is_array($b))throw new AppError('Invalid JSON.');$admin=$u['role']==='admin';if(!$admin&&(!in_array($action,['catalog','downloads','watches','reports','provider-search','provider-detail','delete'])||($action==='delete'&&!in_array($b['entity']??'',['catalog','downloads','watches']))))throw new AppError('Administrator permission required.',403);
 if(in_array($action,['provider-search','provider-detail','provider-test'])){out(providerAction($action,$b));}
 if($action==='upload'){out(uploadImage($b));}
 db()->beginTransaction();try{$result=['saved'=>true];switch($action){
 case 'catalog':$result=saveCatalog($b);break;
 case 'downloads':$result=saveDownload($b);break;
 case 'watches':$result=saveWatch($b);break;
 case 'delete':$table=choice($b['entity']??'', ['catalog','downloads','watches','ads'],null);if(!$table)throw new AppError('Invalid record type.');$id=txt($b['id']??'',36);if(!one('SELECT id FROM cv_'.$table.' WHERE id=?',[$id]))throw new AppError('Record not found.',404);if($table==='catalog')deleteTitle($id);else run('DELETE FROM cv_'.$table.' WHERE id=?',[$id]);audit('Record deleted',$table);break;
 case 'reports':$status=choice($b['status']??null,['resolved','ignored'],'resolved');run('UPDATE cv_reports SET status=?,updated_at=? WHERE id=?',[$status,ms(),$b['id']??'']);audit('Report updated',$status);break;
 case 'ads':$id=$b['id']??uid();if(isset($b['id'])&&!one('SELECT id FROM cv_ads WHERE id=?',[$id]))throw new AppError('Ad not found.',404);$name=txt($b['name']??'',120);$d=$b['data']??[];$data=['provider'=>txt($d['provider']??'',80),'code'=>txt($d['code']??'',30000),'device'=>choice($d['device']??null,['all','desktop','tablet','mobile'],'all'),'start'=>dateval($d['start']??0),'end'=>dateval($d['end']??0),'priority'=>num($d['priority']??0,0,1000),'weight'=>num($d['weight']??null,1,1000,1),'width'=>num($d['width']??0,0,2000),'height'=>num($d['height']??null,50,1200,250)];if(!$name||!$data['code'])throw new AppError('Enter an ad name and code.');if($data['end']&&$data['end']<=$data['start'])throw new AppError('End date must follow start.');$slot=choice($b['slot']??null,['all-pages','homepage-top','homepage-middle','sidebar','movie-top','before-downloads','gateway-top','footer'],'all-pages');$ts=ms();run('INSERT INTO cv_ads VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),slot=VALUES(slot),active=VALUES(active),data=VALUES(data),updated_at=VALUES(updated_at)',[$id,$name,$slot,!empty($b['active'])?1:0,json_encode($data),$ts,$ts]);audit('Advertisement saved',$name);$result=['id'=>$id];break;
 case 'settings':$s=site();$s['name']=txt($b['name']??'',60)?:'CineVault';$s['description']=txt($b['description']??'',300);$s['footerText']=txt($b['footerText']??'',200);foreach(['accent','background','panel','textColor'] as $k){$v=$b[$k]??$s[$k];if(!preg_match('/^#[0-9a-f]{6}$/i',$v))throw new AppError('Use a six-digit color.');$s[$k]=$v;}foreach(['logo','favicon'] as $k)$s[$k]=imageUrl($b[$k]??'');foreach(['facebook','telegram','youtube','instagram'] as $k)$s[$k]=httpsUrl($b[$k]??'');$s['adsEnabled']=!empty($b['adsEnabled']);$s['adRotation']=choice($b['adRotation']??null,['priority','weighted'],'priority');$s['gatewaySeconds']=num($b['gatewaySeconds']??null,0,300,3);saveSetting('site',$s);audit('Site settings updated',$s['name']);break;
 case 'providers':$p=providers();$name=choice($b['provider']??null,['tvmaze','tmdb','omdb'],'tvmaze');$p[$name]=['enabled'=>!empty($b['enabled']),'language'=>txt($b['language']??'en-US',20),'region'=>txt($b['region']??'US',5),'secret'=>!empty($b['clearKey'])?'':(!empty($b['key'])?seal(txt($b['key'],2000)):($p[$name]['secret']??'')),'lastTest'=>null];saveSetting('providers',$p);audit('Provider settings saved',$name);break;
 case 'moderators':$id=$b['id']??uid();$existing=isset($b['id'])?one("SELECT * FROM cv_users WHERE id=? AND role='moderator'",[$id]):null;if(isset($b['id'])&&!$existing)throw new AppError('Moderator not found.',404);$username=strtolower(txt($b['username']??'',60));if(!preg_match('/^[a-z0-9_.-]{3,60}$/',$username))throw new AppError('Use a username of 3–60 letters, digits, dots, underscores or hyphens.');if(one('SELECT id FROM cv_users WHERE username=? AND id<>?',[$username,$id]))throw new AppError('Username already exists.');$pw=(string)($b['password']??'');if((!$existing||$pw!=='')&&strlen($pw)<8)throw new AppError('Use at least 8 password characters.');$hash=$pw!==''?password_hash($pw,PASSWORD_DEFAULT):$existing['verifier'];$ts=ms();run("INSERT INTO cv_users (id,username,name,verifier,role,active,version,created_at,updated_at) VALUES (?,?,?,?,'moderator',?,1,?,?) ON DUPLICATE KEY UPDATE username=VALUES(username),name=VALUES(name),verifier=VALUES(verifier),active=VALUES(active),version=version+1,updated_at=VALUES(updated_at)",[$id,$username,txt($b['name']??'',100),$hash,!empty($b['active'])?1:0,$ts,$ts]);audit('Moderator saved',$username);$result=['id'=>$id];break;
 default:throw new AppError('Unknown action.',404);
 }db()->commit();out($result);}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}
}
function uploadImage(array $b): array {$raw=base64_decode((string)($b['base64']??''),true);if(!$raw||strlen($raw)>524288)throw new AppError('Choose an image under 512 KB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->buffer($raw);$ext=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp','image/x-icon'=>'ico','image/vnd.microsoft.icon'=>'ico'][$mime]??null;if(!$ext)throw new AppError('Use PNG, JPEG, WebP or ICO.');$name=uid().'.'.$ext;$path=dirname(__DIR__).'/media/'.$name;if(file_put_contents($path,$raw,LOCK_EX)===false)throw new AppError('The media folder is not writable.');audit('Image uploaded',$name);return ['url'=>'/media/'.$name];}
