<?php
function remote(string $name,string $path,array $query=[]): array {$p=providers()[$name]??null;if(!$p||empty($p['enabled']))throw new AppError('Enable this provider in Movie APIs first.');$base=['tvmaze'=>'https://api.tvmaze.com','tmdb'=>'https://api.themoviedb.org/3','omdb'=>'https://www.omdbapi.com'][$name];$headers=['Accept: application/json'];if($name!=='tvmaze'){$key=unseal($p['secret']??'');if(!$key)throw new AppError('Add your provider API key in Movie APIs.');if($name==='tmdb'){if(strlen($key)>64)$headers[]='Authorization: Bearer '.$key;else $query['api_key']=$key;$query['language']=$p['language']??'en-US';}else $query['apikey']=$key;}$ch=curl_init($base.$path.'?'.http_build_query($query));curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>15,CURLOPT_HTTPHEADER=>$headers,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);$raw=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($raw===false||$status<200||$status>=300)throw new AppError('Provider request failed. Check the API key, quota, and hosting outbound HTTPS access.',502);$r=json_decode($raw,true);if(!is_array($r)||($r['Response']??'')==='False')throw new AppError('No result found, or API quota reached.',422);return $r;}
function clean($s): string {return ($s==='N/A')?'':trim(html_entity_decode(strip_tags((string)$s),ENT_QUOTES,'UTF-8'));}
function safeImage($s): string {try{return httpsUrl($s);}catch(Throwable $e){return '';}}
function providerAction(string $action,array $b): array {$name=choice($b['provider']??null,['tvmaze','tmdb','omdb'],'tvmaze');$kind=($b['kind']??'movie')==='series'?'series':'movie';$type=$kind==='series'?'tv':'movie';
 if($action==='provider-test'){try{remote($name,$name==='tvmaze'?'/shows/1':($name==='tmdb'?'/configuration':'/'),$name==='omdb'?['i'=>'tt0133093']:[]);$ok=true;$message='Connection verified.';}catch(Throwable $e){$ok=false;$message=$e instanceof AppError?$e->getMessage():'Connection failed.';}$p=providers();$p[$name]['lastTest']=['ok'=>$ok,'message'=>$message,'at'=>ms()];saveSetting('providers',$p);audit('API connection tested',$name);return ['ok'=>$ok,'message'=>$message];}
 if($action==='provider-search'){$q=txt($b['query']??'',150);if(!$q)throw new AppError('Enter a title.');$results=[];if($name==='tvmaze'){foreach(array_slice(remote($name,'/search/shows',['q'=>$q]),0,12) as $x){$r=$x['show'];$results[]=['provider'=>$name,'id'=>(string)$r['id'],'title'=>$r['name'],'kind'=>'series','year'=>(int)substr($r['premiered']??'',0,4),'poster'=>$r['image']['medium']??''];}}elseif($name==='tmdb'){$r=remote($name,'/search/'.$type,['query'=>$q,'include_adult'=>'false']);foreach(array_slice($r['results']??[],0,12) as $x)$results[]=['provider'=>$name,'id'=>(string)$x['id'],'title'=>$x['title']??$x['name'],'kind'=>$kind,'year'=>(int)substr($x['release_date']??$x['first_air_date']??'',0,4),'poster'=>empty($x['poster_path'])?'':'https://image.tmdb.org/t/p/w342'.$x['poster_path']];}else{$r=remote($name,'/',['s'=>$q,'type'=>$kind]);foreach(array_slice($r['Search']??[],0,12) as $x)$results[]=['provider'=>$name,'id'=>$x['imdbID'],'title'=>$x['Title'],'kind'=>$x['Type']==='series'?'series':'movie','year'=>(int)$x['Year'],'poster'=>safeImage($x['Poster'])];}return ['results'=>$results];}
 $id=txt($b['id']??'',40);if(!preg_match($name==='omdb'?'/^tt\d+$/':'/^\d+$/',$id))throw new AppError('Invalid provider ID.');$d=['provider'=>$name,'providerId'=>$id];
 if($name==='tvmaze'){$r=remote($name,'/shows/'.$id,['embed[]'=>'cast']);$title=$r['name'];$kind='series';$d+=['overview'=>clean($r['summary']??''),'year'=>(int)substr($r['premiered']??'',0,4),'releaseDate'=>$r['premiered']??'','runtime'=>$r['averageRuntime']??$r['runtime']??0,'rating'=>$r['rating']['average']??0,'ratingProvider'=>'TVMaze','genres'=>$r['genres']??[],'languages'=>array_filter([$r['language']??'']),'countries'=>array_filter([$r['network']['country']['name']??$r['webChannel']['country']['name']??'']),'poster'=>$r['image']['original']??'','cast'=>implode(', ',array_column(array_column(array_slice($r['_embedded']['cast']??[],0,20),'person'),'name')),'imdbId'=>$r['externals']['imdb']??'','sourceUrl'=>$r['url']??'https://www.tvmaze.com/shows/'.$id];}
 elseif($name==='tmdb'){$r=remote($name,'/'.$type.'/'.$id,['append_to_response'=>'credits,videos,external_ids']);$title=$r['title']??$r['name'];$trailer='';foreach($r['videos']['results']??[] as $v)if($v['site']==='YouTube'&&$v['type']==='Trailer'){$trailer='https://www.youtube.com/watch?v='.rawurlencode($v['key']);break;}$directors=[];$writers=[];foreach($r['credits']['crew']??[] as $c){if(($c['job']??'')==='Director')$directors[]=$c['name'];if(($c['department']??'')==='Writing')$writers[]=$c['name'];}$d+=['originalTitle'=>$r['original_title']??$r['original_name']??'','overview'=>$r['overview']??'','year'=>(int)substr($r['release_date']??$r['first_air_date']??'',0,4),'releaseDate'=>$r['release_date']??$r['first_air_date']??'','runtime'=>$r['runtime']??$r['episode_run_time'][0]??0,'rating'=>$r['vote_average']??0,'ratingProvider'=>'TMDb','genres'=>array_column($r['genres']??[],'name'),'languages'=>array_column($r['spoken_languages']??[],'english_name'),'countries'=>array_column($r['production_countries']??[],'name'),'cast'=>implode(', ',array_column(array_slice($r['credits']['cast']??[],0,20),'name')),'director'=>implode(', ',$directors?:array_column($r['created_by']??[],'name')),'writers'=>implode(', ',array_slice($writers,0,8)),'poster'=>empty($r['poster_path'])?'':'https://image.tmdb.org/t/p/w500'.$r['poster_path'],'backdrop'=>empty($r['backdrop_path'])?'':'https://image.tmdb.org/t/p/w1280'.$r['backdrop_path'],'trailer'=>$trailer,'imdbId'=>$r['imdb_id']??$r['external_ids']['imdb_id']??'','sourceUrl'=>'https://www.themoviedb.org/'.$type.'/'.$id];}
 else{$r=remote($name,'/',['i'=>$id,'plot'=>'full']);$title=$r['Title'];$kind=$r['Type']==='series'?'series':'movie';$d+=['overview'=>clean($r['Plot']??''),'year'=>(int)($r['Year']??0),'releaseDate'=>clean($r['Released']??''),'runtime'=>(int)($r['Runtime']??0),'rating'=>(float)($r['imdbRating']??0),'ratingProvider'=>'IMDb via OMDb','genres'=>listval(clean($r['Genre']??'')),'languages'=>listval(clean($r['Language']??'')),'countries'=>listval(clean($r['Country']??'')),'cast'=>clean($r['Actors']??''),'director'=>clean($r['Director']??''),'writers'=>clean($r['Writer']??''),'poster'=>safeImage($r['Poster']??''),'imdbId'=>$id,'sourceUrl'=>'https://www.imdb.com/title/'.$id.'/'];}
 return ['record'=>['title'=>$title,'kind'=>$kind,'status'=>'draft','data'=>$d]];
}
